# -*- coding: utf-8 -*-
"""Copy of Sentiment_analysis movie

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ik47M-QWtNaAg--IGHF_zFse2P0UubrR
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
fredericobreno_play_tennis_path = kagglehub.dataset_download('fredericobreno/play-tennis')
lakshmi25npathi_imdb_dataset_of_50k_movie_reviews_path = kagglehub.dataset_download('lakshmi25npathi/imdb-dataset-of-50k-movie-reviews')

print('Data source import complete.')

pip install kagglehub[pandas-datasets]

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

import kagglehub
path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")
print("path to dataset files:",path)

df = pd.read_csv(path +'/IMDB Dataset.csv')
df.head()



df.shape

df["sentiment"].replace({"positive":1,"negative":0},inplace=True)
df.head()

negative_words = {
    # Basic negations
    "no", "not", "nor", "never", "none", "nobody", "nothing", "nowhere",
    "neither", "without",

    # Limited negations
    "hardly", "scarcely", "barely", "rarely", "seldom",

    # Contracted negations
    "isn't", "aren't", "wasn't", "weren't", "haven't", "hasn't", "hadn't",
    "doesn't", "don't", "didn't", "won't", "wouldn't", "shouldn't", "couldn't",
    "can't", "cannot", "mustn't", "mightn't", "shan't",

    # NLTK common negative words
    "against", "alone", "awful", "bad", "bare", "barren", "boring", "broken",
    "cruel", "dead", "defeated", "denied", "desperate", "difficult", "dirty",
    "disappointing", "disastrous", "dishonest", "dull", "empty", "evil",
    "fail", "faulty", "fear", "feeble", "futile", "gloomy", "grave", "greedy",
    "grim", "guilty", "harsh", "hate", "hideous", "hopeless", "horrible",
    "hostile", "ignorant", "imperfect", "impossible", "inferior", "injured",
    "jealous", "lacking", "lose", "losing", "loss", "mean", "messy", "missing",
    "miserable", "naive", "nasty", "negative", "never", "no", "nobody",
    "none", "not", "nothing", "nowhere", "offensive", "opposite", "painful",
    "pathetic", "pessimistic", "petty", "plain", "poor", "reckless", "reject",
    "repulsive", "rough", "sad", "scary", "selfish", "sick", "silly", "sinful",
    "slow", "sour", "stubborn", "stupid", "tense", "terrible", "threatening",
    "ugly", "unable", "unacceptable", "unaware", "unfair", "unfortunate",
    "unhappy", "unhealthy", "unjust", "unkind", "unlucky", "unpleasant",
    "unsatisfactory", "unwanted", "unworthy", "upset", "vicious", "vulnerable",
    "weak", "worthless", "worse", "worst", "wrong",

    # Intensifiers that often accompany negativity
    "absolutely", "completely", "totally", "utterly", "extremely", "terribly",
    "horribly", "awfully", "dreadfully",

    # Negative prefixes (for pattern matching)
    "un", "dis", "non", "in", "im", "il", "ir", "anti", "de", "mis", "mal",

    # Common negative phrases
    "no longer", "not at all", "by no means", "in no way", "under no circumstances",

    # Emotional negative words
    "angry", "annoyed", "frustrated", "disappointed", "disgusted", "outraged",
    "furious", "irritated", "upset", "depressed", "anxious", "worried", "stressed",
    "afraid", "fearful", "terrified", "horrified", "ashamed", "guilty", "regretful",

    # Negative verbs
    "hate", "detest", "loathe", "despise", "abhor", "dislike", "reject", "deny",
    "refuse", "oppose", "resist", "complain", "criticize", "blame", "accuse",

    # Negative adjectives
    "awful", "terrible", "horrible", "dreadful", "atrocious", "appalling",
    "disgusting", "revolting", "repulsive", "offensive", "vile", "nasty",
    "unpleasant", "disagreeable", "distasteful", "objectionable", "deplorable",
    "lamentable", "regrettable", "unfortunate", "unlucky", "tragic", "catastrophic",
    "disastrous", "ruinous", "calamitous", "devastating", "harmful", "damaging",
    "destructive", "injurious", "detrimental", "adverse", "negative", "bad",
    "poor", "inferior", "substandard", "unsatisfactory", "inadequate", "deficient",
    "defective", "faulty", "flawed", "imperfect", "unsound", "unreliable",
    "untrustworthy", "deceitful", "dishonest", "fraudulent", "corrupt", "unethical",
    "immoral", "sinful", "wicked", "evil", "vicious", "cruel", "brutal", "savage",
    "ruthless", "merciless", "heartless", "callous", "cold", "unkind", "mean",
    "spiteful", "malicious", "malevolent", "hostile", "aggressive", "violent",
    "abusive", "oppressive", "tyrannical", "dictatorial", "authoritarian",

    # Additional comprehensive negative terms
    "abandon", "abuse", "accident", "ache", "agony", "alarm", "anger", "anguish",
    "annoyance", "anxiety", "apathy", "apprehension", "argument", "assault",
    "aversion", "betrayal", "bitterness", "blame", "bleak", "bloody", "blunder",
    "bother", "break", "burden", "cancer", "careless", "chaos", "cheat", "clumsy",
    "collapse", "conflict", "confuse", "contradiction", "corruption", "crime",
    "crisis", "criticism", "crowded", "cruelty", "cry", "damage", "danger",
    "dark", "deadly", "deceive", "defeat", "defect", "degrade", "delay", "denial",
    "depress", "derail", "despair", "destroy", "deteriorate", "devastate",
    "difficulty", "dilemma", "disadvantage", "disagree", "disappear", "disaster",
    "discomfort", "discourage", "disease", "disgrace", "dishonor", "dislike",
    "dismay", "disorder", "displease", "dispute", "disrupt", "distress", "distrust",
    "disturb", "doubt", "downfall", "drain", "dread", "dreary", "dull", "dumb",
    "eerie", "embarrass", "emergency", "enemy", "error", "evil", "exhaust",
    "exploit", "failure", "fake", "fall", "false", "fatal", "fatigue", "fear",
    "flaw", "flee", "fool", "forbid", "force", "foul", "fragile", "fraud", "fright",
    "frustrate", "grief", "grim", "gross", "grouchy", "guilt", "hardship", "harm",
    "hate", "hatred", "haunt", "hazard", "helpless", "hideous", "hinder", "hopeless",
    "hostile", "humiliate", "hunger", "hurt", "ignore", "ill", "illness", "impair",
    "impossible", "impulse", "incompetent", "inconvenient", "indecent", "infection",
    "inferior", "injury", "insane", "insult", "intrude", "irrational", "irritate",
    "jealous", "junk", "kill", "lack", "lazy", "lethal", "liar", "limitation",
    "lonely", "lose", "loss", "loud", "lousy", "lumpy", "mad", "malice", "malignant",
    "mania", "massacre", "meltdown", "mess", "miserable", "misery", "miss", "mistake",
    "moan", "mock", "molest", "monstrous", "moody", "mortal", "mourn", "murder",
    "nasty", "naughty", "negative", "nervous", "nightmare", "objection", "obscene",
    "obsess", "obstacle", "odd", "offend", "oppress", "outrage", "overwhelm",
    "pain", "panic", "paranoid", "passive", "peril", "pessimistic", "petty",
    "phobia", "plague", "poison", "pollute", "poor", "prejudice", "problem",
    "protest", "punish", "quarrel", "radical", "rage", "ragged", "rash", "raw",
    "rebel", "recession", "reckless", "refuse", "regret", "reject", "relentless",
    "repel", "repulsive", "resign", "restless", "revenge", "revolting", "revolution",
    "risk", "rotten", "rough", "rude", "ruin", "ruthless", "sad", "savage", "scandal",
    "scare", "scream", "severe", "shabby", "shame", "shatter", "shock", "short",
    "shrill", "sick", "sickening", "sin", "slavery", "slimy", "sloppy", "smelly",
    "smother", "sob", "sore", "sorrow", "spill", "spite", "stab", "stagnant",
    "stain", "stale", "sting", "stink", "stress", "strict", "strike", "struggle",
    "stubborn", "stuck", "stun", "subordinate", "suffer", "suicide", "superficial",
    "suspect", "suspicious", "tension", "terrible", "terror", "threat", "thrifty",
    "tired", "tragic", "traitor", "trash", "trauma", "treason", "trick", "trivial",
    "trouble", "turbulent", "ugly", "unaware", "uncertain", "uncomfortable",
    "unconscious", "undermine", "uneasy", "unemployment", "unfair", "unfortunate",
    "unhappy", "unhealthy", "unjust", "unkind", "unlucky", "unpleasant", "unreliable",
    "unsafe", "unstable", "unwanted", "unwelcome", "unwise", "upset", "useless",
    "vague", "vain", "vicious", "victim", "violate", "violent", "vulnerable",
    "waste", "weak", "weary", "weep", "weird", "wicked", "worthless", "wound",
    "wreck", "wretched", "yell", "yucky", "zero"
}

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
nltk.download("stopwords")

# removing the html tags
def remove_tags(text):
  clean = re.compile('<.*?>')
  return re.sub(clean,'',text)

# converting into lower case
def convert_lower(text):
  return text.lower()

#Remove special character
def clean_text(text, remove_numbers=True):
    if not isinstance(text, str):
        raise ValueError("Input must be a string")
    # Remove special characters first (replace with spaces)
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    # Remove numbers if requested - do this AFTER special character removal
    if remove_numbers:
        text = re.sub(r'\d+', ' ', text)  # Replace numbers with spaces
    # Remove extra spaces that might have been created
    text = re.sub(r'\s+', ' ', text).strip()
    return text


def remove_stopwords(text, negative_words):
    """
    Remove stopwords but keep negative words (optimized)
    """
    from nltk.corpus import stopwords

    sw = set(stopwords.words('english'))
    return [word for word in text.split()
            if word.lower() not in sw or word.lower() in negative_words]

#creating the stemword
def stem_text(text):
    ps = PorterStemmer()
    result = []  # ← LOCAL VARIABLE (CORRECT)
    for word in text:
        result.append(ps.stem(word))
    return result

df["review"] = df["review"].apply(remove_tags)

df["review"] = df["review"].apply(convert_lower)

df["review"] = df["review"].apply( clean_text)

df.head()

df["review"] = df["review"].apply(lambda x: remove_stopwords(x, negative_words))

df.head()

df.shape

df["review"] = df["review"].apply(stem_text)

df.head()

def join_text(list_input):
  return " ".join(list_input)

df["review"] = df["review"].apply(join_text)

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=3000)
X=cv.fit_transform(df["review"]).toarray()

X.shape

y=df.iloc[:,-1].values

y.shape

X[0].max()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

print("for train")
print(X_train.shape)
print(y_train.shape)
print()
print("for test")
print(X_test.shape)
print(y_test.shape)

from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train,y_train)

y_predict = model.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test, y_predict))

print(confusion_matrix(y_test, y_predict))

print(classification_report(y_predict,y_test))

from sklearn.metrics import precision_score, recall_score
print(precision_score(y_test, y_predict))
print(recall_score(y_test, y_predict))

from sklearn.naive_bayes import MultinomialNB

model1 = MultinomialNB()
model1.fit(X_train, y_train)
y1_predict = model1.predict(X_test)
acc = accuracy_score(y_test, y1_predict)

y1_predict = model1.predict(X_test)
print(accuracy_score(y_test,y1_predict))

print(confusion_matrix(y_test, y1_predict))

print(classification_report(y1_predict,y_test))

from sklearn.naive_bayes import BernoulliNB
model2 = BernoulliNB()
model2.fit(X_train, y_train)

y2_predict = model2.predict(X_test)
print(accuracy_score(y_test,y2_predict))

print(confusion_matrix(y_test,y2_predict))

print(classification_report(y2_predict,y_test))

# Single review as a list
reviews = ["This was a terrible experience. The product broke after one day and I am very disappointed."]
X_input = cv.transform(reviews)
# Predict sentiment
prediction = model1.predict(X_input)
print(prediction)

positive_reviews = [
    "I absolutely loved this product! The quality is excellent and it made me very happy.",
    "Amazing experience! Totally worth the money and I would recommend it to everyone.",
    "This is the best thing I have bought this year, super satisfied.",
    "Excellent quality and fast delivery. I am impressed!",
    "Five stars! The service was fantastic and the staff was friendly.",
    "Really good product, works as expected and I will buy again.",
    "I had a wonderful time, everything was smooth and well organized.",
    "Love it! Beautiful design and great performance.",
    "Very happy with my purchase, exactly as described.",
    "Top-notch quality, exceeded my expectations!"
]
positive_reviews.extend([
    "This movie was so good I want to watch it again!",
    "Brilliant performance by the cast, really brought the story to life.",
    "I’m so glad I tried this, it was better than I expected.",
    "Fantastic experience from start to finish, highly recommend.",
    "This exceeded my expectations in every way possible.",
    "Incredible product, worth every penny!",
    "Everything worked perfectly, couldn’t be happier.",
    "Absolutely amazing, 10/10 would recommend to my friends.",
    "Perfect choice, I’m extremely satisfied with the result.",
    "Beautifully made and exactly what I needed.",
    "Loved every minute of it, such a great experience.",
    "It was fun, entertaining, and well worth my time.",
    "Impressive quality and attention to detail.",
    "Everything was flawless, I will definitely come back.",
    "Such a delightful surprise, I’m very pleased!"
])


for reviews in positive_reviews:
    X_input = cv.transform([reviews]).toarray()
    prediction = model2.predict(X_input)
    print(prediction)

negative_reviews = [
    "This was a terrible experience. The product broke after one day and I am very disappointed.",
    "Worst purchase ever, complete waste of money.",
    "The quality was awful and it arrived late.",
    "I had a bad experience, customer service was unhelpful.",
    "One star. It did not work as promised and I want a refund.",
    "Very poor quality, looks nothing like the pictures.",
    "Extremely disappointed, I will never buy from here again.",
    "The product is defective and useless.",
    "Horrible service, no response from support team.",
    "Cheap and badly made, don't buy this."
]
negative_reviews.extend([
    "Completely unsatisfied, this was a total letdown.",
    "The item stopped working after just a week, very frustrating.",
    "I regret spending money on this, not worth it.",
    "Terrible quality, feels cheap and unreliable.",
    "Very bad experience, shipping was delayed and item was broken.",
    "Absolutely horrible, I wish I could give zero stars.",
    "Customer service ignored my complaint, very unprofessional.",
    "This was so disappointing, I expected much better.",
    "Do not waste your money, it's a scam.",
    "Everything about this purchase was wrong — never again.",
    "I am not happy with this at all, it failed completely.",
    "It broke the first time I used it, very poor design.",
    "The product description was misleading and I feel cheated.",
    "Nothing good about this experience, I want my money back.",
    "It was a disaster from start to finish, horrible quality."
])


for reviews in negative_reviews:
    X_input = cv.transform([reviews]).toarray()
    prediction = model2.predict(X_input)
    print(prediction)

# if the label is ballenced or not
import numpy as np
unique, counts = np.unique(y_train, return_counts=True)
print(dict(zip(unique, counts)))

import pickle
def save_model(cv, model, negative_words, filename='sentiment_model.pkl'):
    """
    Save a single sentiment analysis model with all necessary components
    """
    pipeline = {
        'vectorizer': cv,
        'model': model,
        'negative_words': negative_words,
        'metadata': {
            'created_date': pd.Timestamp.now().strftime('%Y-%m-%d'),
            'model_type': type(model).__name__,
            'vectorizer_type': type(cv).__name__
        }
    }

    with open(filename, 'wb') as f:
        pickle.dump(pipeline, f)

    print(f"Model saved to {filename}")
    return filename

save_model(cv,model2,"sentiment_model1.pkl")

# loading model
def load_single_model(filename='sentiment_model.pkl'):
    """
    Load the saved sentiment analysis model
    """
    with open(filename, 'rb') as f:
        pipeline = pickle.load(f)

    print(f"Model loaded: {pipeline['metadata']['model_type']}")
    return pipeline

pipeline = load_single_model()
cv = pipeline['vectorizer']
model = pipeline['model']
negative_words = pipeline['negative_words']

# prediction
def predict_sentiment(text, cv, model, negative_words):
    """
    Predict sentiment using the single model
    """
    if isinstance(text, str):
        text = [text]

    # Transform text
    X_input = cv.transform(text).toarray()

    # Get predictions
    predictions = model.predict(X_input)

    # Convert to sentiment labels
    sentiment_labels = []
    for pred in predictions:
        if pred == 1:
            sentiment_labels.append("positive")
        else:
            sentiment_labels.append("negative")

    return sentiment_labels

texts = ["Very bad experience, shipping was delayed and item was broken."]
predictions = predict_sentiment(texts, cv, model, negative_words)
print(predictions)

